apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD_BASE64}"
  MYSQL_DATABASE: "${MYSQL_DATABASE_BASE64}"
  MYSQL_USER: "${MYSQL_USER_BASE64}"
  MYSQL_PASSWORD: "${MYSQL_PASSWORD_BASE64}"
