name: CI - Build & Push Images

on:
  push:
    branches: [main, test]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u fakraze --password-stdin

      - name: Build & Push Frontend
        run: |
          docker build -t ghcr.io/fakraze/cloud-meal-frontend:latest ./frontend
          docker push ghcr.io/fakraze/cloud-meal-frontend:latest

      - name: Build & Push Backend
        run: |
          docker build -t ghcr.io/fakraze/cloud-meal-backend:latest ./backend
          docker push ghcr.io/fakraze/cloud-meal-backend:latest
